"""add forecasts

Revision ID: 253a9ea62f98
Revises: 41e62d6b1321
Create Date: 2025-11-26 16:18:52.001663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253a9ea62f98'
down_revision: Union[str, Sequence[str], None] = '41e62d6b1321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_house_series',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('job_id', 'house_id', 'timestamp', name='forecast_house_series_pkey')
    )
    op.create_index('ix_forecast_house_series_house', 'forecast_house_series', ['house_id'], unique=False)
    op.create_index(op.f('ix_forecast_house_series_job_id'), 'forecast_house_series', ['job_id'], unique=False)
    op.drop_index(op.f('ix_forecast_series_timestamp'), table_name='forecast_series')
    op.drop_column('forecast_series', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_series', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_forecast_series_timestamp'), 'forecast_series', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_forecast_house_series_job_id'), table_name='forecast_house_series')
    op.drop_index('ix_forecast_house_series_house', table_name='forecast_house_series')
    op.drop_table('forecast_house_series')
    # ### end Alembic commands ###
