"""files added

Revision ID: a4adc509eeb1
Revises: 13dcb78dd731
Create Date: 2025-11-20 12:54:16.326619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4adc509eeb1'
down_revision: Union[str, Sequence[str], None] = '13dcb78dd731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('prepared_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_batch_id'), 'file_uploads', ['batch_id'], unique=False)
    op.create_index(op.f('ix_file_uploads_status'), 'file_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_file_uploads_user_id'), 'file_uploads', ['user_id'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prepared_path', sa.String(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_batches_status'), 'ingestion_batches', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_batches_user_id'), 'ingestion_batches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_batches_user_id'), table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_status'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_index(op.f('ix_file_uploads_user_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_status'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_batch_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
