"""add forecasts


Revision ID: b673e04295fd
Revises: 9a905c603981
Create Date: 2025-11-26 15:17:53.653285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b673e04295fd'
down_revision: Union[str, Sequence[str], None] = '9a905c603981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_jobs_batch_id'), 'forecast_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_forecast_jobs_status'), 'forecast_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_forecast_jobs_user_id'), 'forecast_jobs', ['user_id'], unique=False)
    op.create_table('forecast_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_series_job_id'), 'forecast_series', ['job_id'], unique=False)
    op.create_index(op.f('ix_forecast_series_timestamp'), 'forecast_series', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_series_timestamp'), table_name='forecast_series')
    op.drop_index(op.f('ix_forecast_series_job_id'), table_name='forecast_series')
    op.drop_table('forecast_series')
    op.drop_index(op.f('ix_forecast_jobs_user_id'), table_name='forecast_jobs')
    op.drop_index(op.f('ix_forecast_jobs_status'), table_name='forecast_jobs')
    op.drop_index(op.f('ix_forecast_jobs_batch_id'), table_name='forecast_jobs')
    op.drop_table('forecast_jobs')
    # ### end Alembic commands ###
