"""init

Revision ID: bd8cfc04ee04
Revises: a4adc509eeb1
Create Date: 2025-11-24 14:16:23.760723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8cfc04ee04'
down_revision: Union[str, Sequence[str], None] = 'a4adc509eeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_reports_batch_id'), 'data_quality_reports', ['batch_id'], unique=False)
    op.create_index(op.f('ix_data_quality_reports_user_id'), 'data_quality_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_quality_reports_user_id'), table_name='data_quality_reports')
    op.drop_index(op.f('ix_data_quality_reports_batch_id'), table_name='data_quality_reports')
    op.drop_table('data_quality_reports')
    # ### end Alembic commands ###
